# Generated by Django 5.2.8 on 2025-12-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "parties",
            },
        ),
        migrations.CreateModel(
            name="OddsReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("odds", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "bookmaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="polls.bookmaker",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="polls.party"
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "party", "bookmaker"],
                "indexes": [
                    models.Index(fields=["date"], name="idx_odds_date"),
                    models.Index(fields=["date", "party"], name="idx_odds_date_party"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "bookmaker", "party"),
                        name="unique_daily_reading",
                    )
                ],
            },
        ),
    ]
