# Generated by Django 5.2.8 on 2026-01-03 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketConsensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('fair_probability', models.DecimalField(decimal_places=4, max_digits=6)),
                ('averaged_odds', models.DecimalField(decimal_places=4, max_digits=8)),
                ('bookmaker_count', models.PositiveSmallIntegerField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.party')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'party'], name='polls_marke_timesta_92fe67_idx')],
                'unique_together': {('timestamp', 'party')},
            },
        ),
    ]
