"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")

# =============================================================================
# SECURITY SETTINGS
# =============================================================================

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECRET_KEY: Used for cryptographic signing (sessions, CSRF tokens, etc.)
# In production, set this via environment variable - never commit real keys!
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is not set")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG: Shows detailed error pages. MUST be False in production.
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() == "true"

# ALLOWED_HOSTS: Domains that can serve this app.
# - Empty in dev (Django allows localhost when DEBUG=True)
# - In production, add your domain and server IP
ALLOWED_HOSTS = list(filter(None, os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")))

# If no hosts specified and we're in debug mode, allow localhost
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# Security settings only for production:
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# =============================================================================
# APPLICATION DEFINITION
# =============================================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Local apps
    "polls.apps.PollsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # DIRS: Project-level templates (e.g., base.html shared across apps)
        "DIRS": [BASE_DIR / "templates"],
        # APP_DIRS: Look for templates in each app's 'templates' subdir
        "APP_DIRS": True,
        # OPTIONS: Context processors for template rendering
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# =============================================================================
# DATABASE
# =============================================================================
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite for simplicity - works great for your minimal records/day volume
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# =============================================================================
# PASSWORD VALIDATION
# =============================================================================
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# =============================================================================
# INTERNATIONALIZATION
# =============================================================================
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-au"

# TIME_ZONE: All datetimes stored/displayed in Sydney time
# Critical for your scraping schedule and displaying odds timestamps
TIME_ZONE = "Australia/Sydney"

USE_I18N = True

# USE_TZ: Store datetimes as UTC in DB, convert to TIME_ZONE for display
# Best practice - keeps data consistent regardless of server location
USE_TZ = True




# =============================================================================
# STATIC FILES (CSS, JavaScript, Images)
# =============================================================================
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL prefix for static files
STATIC_URL = "static/"

# STATICFILES_DIRS: Where Django looks for static files during development
# Put your CSS, JS, images here (e.g., HTMX, custom styles)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# STATIC_ROOT: Where `collectstatic` copies all static files for production
# nginx will serve files from this directory
STATIC_ROOT = BASE_DIR / "staticfiles"


# =============================================================================
# DEFAULT PRIMARY KEY
# =============================================================================
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =============================================================================
# CSRF SETTINGS (Important for HTMX)
# =============================================================================

# HTMX sends AJAX requests that need CSRF tokens
# This setting allows CSRF token to be read from a cookie by JavaScript
CSRF_COOKIE_HTTPONLY = False  # Allow JS to read the CSRF cookie



